
import urllib.request
import urllib.error
import json
import ssl
import time

SUPABASE_URL = 'https://djteatwxjlnbjylynvjh.supabase.co'
SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqdGVhdHd4amxuYmp5bHludmpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkwODUwOTMsImV4cCI6MjA5NDY2MTA5M30.P6IJW2noTImzeNXtfKsmjJBMp9AJBTw1LamYTdtyd_4'

ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

def import_major(major):
    url = f'{SUPABASE_URL}/rest/v1/majors'
    data = json.dumps(major).encode('utf-8')
    req = urllib.request.Request(url, data=data, method='POST')
    req.add_header('apikey', SUPABASE_KEY)
    req.add_header('Authorization', f'Bearer {SUPABASE_KEY}')
    req.add_header('Content-Type', 'application/json')
    req.add_header('Prefer', 'return=minimal')
    try:
        with urllib.request.urlopen(req, context=ctx) as response:
            return True, response.status
    except urllib.error.HTTPError as e:
        return False, e.code if e.code != 409 else 409

majors_to_add = [
    {
        'code': '100101T',
        'name': '基础医学',
        'category': '10 医学',
        'category_icon': '🏥',
        'difficulty': '⭐⭐⭐',
        'salary_range': '¥8k-25k',
        'overview': '基础医学专业培养掌握基础医学知识的人才，从事医学研究和教学工作。',
        'what_you_learn': '人体解剖学、组织胚胎学、生理学、生物化学、微生物学、病理学',
        'suitable_for': '对医学和科研有兴趣的学生。',
        'career_outlook': '医院、科研机构等对基础医学人才有需求。',
        'xuefeng_comment': '基础医学是医学类专业，就业稳定。建议对医学研究有兴趣的同学报考。',
        'yearly_courses': {'大一': ['系统解剖学、组织胚胎学、生理学、生物化学'], '大二': ['微生物学、免疫学、病理学、病理生理学'], '大三': ['药理学、诊断学、医学统计学、医学文献检索'], '大四': ['医院实习', '毕业论文']},
        'top_universities': {'domestic': ['北京协和医学院、北京大学、复旦大学、上海交通大学'], 'international': ['哈佛大学、约翰霍普金斯大学、牛津大学']}
    },
    {
        'code': '100102T',
        'name': '生物医学',
        'category': '10 医学',
        'category_icon': '🧬',
        'difficulty': '⭐⭐⭐',
        'salary_range': '¥9k-30k',
        'overview': '生物医学专业培养掌握生物医学知识的人才，从事生物医学研究和应用工作。',
        'what_you_learn': '生物化学、分子生物学、细胞生物学、生理学、医学统计学、生物医学工程',
        'suitable_for': '对生物医学有兴趣的学生。',
        'career_outlook': '科研机构、医药企业等对生物医学人才有需求。',
        'xuefeng_comment': '生物医学是交叉专业，前景好。建议对生物医学有兴趣的同学报考。',
        'yearly_courses': {'大一': ['高等数学、大学物理、无机化学、有机化学'], '大二': ['生物化学、分子生物学、细胞生物学、生理学'], '大三': ['医学统计学、生物医学工程、分子遗传学'], '大四': ['科研机构实习', '毕业论文']},
        'top_universities': {'domestic': ['清华大学、北京大学、上海交通大学、浙江大学'], 'international': ['麻省理工学院、斯坦福大学、哈佛大学']}
    },
    {
        'code': '100103T',
        'name': '生物医学科学',
        'category': '10 医学',
        'category_icon': '🧬',
        'difficulty': '⭐⭐⭐',
        'salary_range': '¥9k-28k',
        'overview': '生物医学科学专业培养掌握生物医学科学知识的人才，从事相关研究和应用工作。',
        'what_you_learn': '生物化学、分子生物学、细胞生物学、生理学、遗传学、免疫学',
        'suitable_for': '对生物医学科学有兴趣的学生。',
        'career_outlook': '科研机构、医药企业等对生物医学科学人才有需求。',
        'xuefeng_comment': '生物医学科学是新兴专业，前景好。建议对生物医学有兴趣的同学报考。',
        'yearly_courses': {'大一': ['高等数学、大学物理、无机化学、有机化学'], '大二': ['生物化学、分子生物学、细胞生物学、生理学'], '大三': ['遗传学、免疫学、微生物学、医学统计学'], '大四': ['科研机构实习', '毕业论文']},
        'top_universities': {'domestic': ['清华大学、北京大学、上海交通大学、浙江大学'], 'international': ['麻省理工学院、斯坦福大学、哈佛大学']}
    },
    {
        'code': '100201T',
        'name': '临床医学',
        'category': '10 医学',
        'category_icon': '🏥',
        'difficulty': '⭐⭐⭐⭐',
        'salary_range': '¥10k-35k',
        'overview': '临床医学专业培养掌握临床医学知识的医生，从事疾病诊疗工作。',
        'what_you_learn': '人体解剖学、生理学、病理学、药理学、诊断学、内科学、外科学',
        'suitable_for': '对医学和医生职业有兴趣的学生。',
        'career_outlook': '医院、诊所等对临床医学人才有大量需求。',
        'xuefeng_comment': '临床医学是医学类核心专业，就业非常好。建议对医学有兴趣的同学报考。',
        'yearly_courses': {'大一': ['系统解剖学、组织胚胎学、生理学、生物化学'], '大二': ['病理学、病理生理学、药理学、微生物学'], '大三': ['诊断学、内科学、外科学、妇产科学'], '大四': ['儿科学、神经病学、传染病学、医院实习'], '大五': ['医院实习', '毕业论文']},
        'top_universities': {'domestic': ['北京协和医学院、北京大学、复旦大学、上海交通大学'], 'international': ['哈佛大学、约翰霍普金斯大学、牛津大学']}
    },
    {
        'code': '100202T',
        'name': '麻醉学',
        'category': '10 医学',
        'category_icon': '💊',
        'difficulty': '⭐⭐⭐⭐',
        'salary_range': '¥10k-35k',
        'overview': '麻醉学专业培养掌握麻醉学知识的医生，从事麻醉工作。',
        'what_you_learn': '麻醉学、药理学、生理学、外科学、内科学、疼痛诊疗学',
        'suitable_for': '对麻醉学有兴趣的学生。',
        'career_outlook': '医院麻醉科等对麻醉学人才有需求。',
        'xuefeng_comment': '麻醉学是医学类专业，就业好，待遇高。建议对麻醉学有兴趣的同学报考。',
        'yearly_courses': {'大一': ['系统解剖学、组织胚胎学、生理学、生物化学'], '大二': ['病理学、病理生理学、药理学、微生物学'], '大三': ['麻醉学、外科学、内科学、疼痛诊疗学'], '大四': ['临床麻醉学、急救医学、医院实习'], '大五': ['医院实习', '毕业论文']},
        'top_universities': {'domestic': ['北京协和医学院、北京大学、复旦大学、上海交通大学'], 'international': ['哈佛大学、约翰霍普金斯大学、斯坦福大学']}
    },
    {
        'code': '100203T',
        'name': '医学影像学',
        'category': '10 医学',
        'category_icon': '📷',
        'difficulty': '⭐⭐⭐',
        'salary_range': '¥9k-28k',
        'overview': '医学影像学专业培养掌握医学影像学知识的医生，从事医学影像诊断工作。',
        'what_you_learn': '医学影像学、医学影像技术、放射诊断学、超声诊断学、核医学',
        'suitable_for': '对医学影像学有兴趣的学生。',
        'career_outlook': '医院影像科等对医学影像学人才有需求。',
        'xuefeng_comment': '医学影像学是医学类专业，就业好，工作环境相对干净。建议对医学影像有兴趣的同学报考。',
        'yearly_courses': {'大一': ['系统解剖学、生理学、生物化学、物理学'], '大二': ['病理学、诊断学、医学影像技术学、放射诊断学'], '大三': ['超声诊断学、核医学、医学影像设备学'], '大四': ['医院实习', '毕业论文']},
        'top_universities': {'domestic': ['复旦大学、上海交通大学、华中科技大学、四川大学'], 'international': ['哈佛大学、约翰霍普金斯大学、斯坦福大学']}
    },
    {
        'code': '100204T',
        'name': '眼视光医学',
        'category': '10 医学',
        'category_icon': '👁️',
        'difficulty': '⭐⭐⭐',
        'salary_range': '¥9k-30k',
        'overview': '眼视光医学专业培养掌握眼视光医学知识的医生，从事眼视光诊疗工作。',
        'what_you_learn': '眼科学、视光学、眼镜学、眼视光器械学、双眼视觉学',
        'suitable_for': '对眼视光医学有兴趣的学生。',
        'career_outlook': '医院眼科、视光中心等对眼视光医学人才有需求。',
        'xuefeng_comment': '眼视光医学是医学类专业，就业好，需求增长。建议对眼视光有兴趣的同学报考。',
        'yearly_courses': {'大一': ['系统解剖学、生理学、生物化学、物理学'], '大二': ['眼科学基础、视光学基础、眼镜学、眼视光器械学'], '大三': ['眼科学、双眼视觉学、斜视弱视学'], '大四': ['医院实习', '毕业论文']},
        'top_universities': {'domestic': ['温州医科大学、四川大学、上海交通大学、中山大学'], 'international': ['哈佛大学、约翰霍普金斯大学、伦敦帝国学院']}
    },
    {
        'code': '100205T',
        'name': '精神医学',
        'category': '10 医学',
        'category_icon': '🧠',
        'difficulty': '⭐⭐⭐',
        'salary_range': '¥9k-28k',
        'overview': '精神医学专业培养掌握精神医学知识的医生，从事精神疾病诊疗工作。',
        'what_you_learn': '精神病学、心理学、心理治疗学、精神药理学、神经病学',
        'suitable_for': '对精神医学有兴趣的学生。',
        'career_outlook': '医院精神科、心理卫生中心等对精神医学人才有需求。',
        'xuefeng_comment': '精神医学是医学类专业，需求增长。建议对精神医学有兴趣的同学报考。',
        'yearly_courses': {'大一': ['系统解剖学、生理学、生物化学、心理学'], '大二': ['精神病学基础、病理学、诊断学、心理学'], '大三': ['精神病学、心理治疗学、精神药理学、神经病学'], '大四': ['医院实习', '毕业论文']},
        'top_universities': {'domestic': ['中南大学、上海交通大学、北京大学、首都医科大学'], 'international': ['哈佛大学、斯坦福大学、伦敦国王学院']}
    },
    {
        'code': '100206T',
        'name': '放射医学',
        'category': '10 医学',
        'category_icon': '☢️',
        'difficulty': '⭐⭐⭐',
        'salary_range': '¥9k-26k',
        'overview': '放射医学专业培养掌握放射医学知识的医生，从事放射诊疗和防护工作。',
        'what_you_learn': '放射物理学、放射生物学、放射治疗学、医学影像学、核医学',
        'suitable_for': '对放射医学有兴趣的学生。',
        'career_outlook': '医院放射科、放疗科等对放射医学人才有需求。',
        'xuefeng_comment': '放射医学是医学类专业，就业稳定。建议对放射医学有兴趣的同学报考。',
        'yearly_courses': {'大一': ['系统解剖学、生理学、生物化学、物理学'], '大二': ['放射物理学、放射生物学、病理学、诊断学'], '大三': ['放射治疗学、医学影像学、核医学'], '大四': ['医院实习', '毕业论文']},
        'top_universities': {'domestic': ['苏州大学、复旦大学、上海交通大学、华中科技大学'], 'international': ['哈佛大学、约翰霍普金斯大学、斯坦福大学']}
    },
    {
        'code': '100207T',
        'name': '预防医学',
        'category': '10 医学',
        'category_icon': '🌡️',
        'difficulty': '⭐⭐⭐',
        'salary_range': '¥7k-22k',
        'overview': '预防医学专业培养掌握预防医学知识的人才，从事公共卫生工作。',
        'what_you_learn': '流行病学、卫生统计学、环境卫生学、职业卫生学、营养与食品卫生学',
        'suitable_for': '对预防医学和公共卫生有兴趣的学生。',
        'career_outlook': '疾控中心、医院、卫生部门等对预防医学人才有需求。',
        'xuefeng_comment': '预防医学是医学类专业，就业稳定。建议对预防医学有兴趣的同学报考。',
        'yearly_courses': {'大一': ['系统解剖学、生理学、生物化学、无机化学'], '大二': ['卫生统计学、流行病学、环境卫生学、职业卫生学'], '大三': ['营养与食品卫生学、儿童少年卫生学、卫生毒理学'], '大四': ['疾控中心实习', '毕业论文']},
        'top_universities': {'domestic': ['北京大学、复旦大学、华中科技大学、南京医科大学'], 'international': ['哈佛大学、约翰霍普金斯大学、伦敦帝国学院']}
    },
    {
        'code': '100208T',
        'name': '妇幼保健医学',
        'category': '10 医学',
        'category_icon': '👶',
        'difficulty': '⭐⭐⭐',
        'salary_range': '¥7k-22k',
        'overview': '妇幼保健医学专业培养掌握妇幼保健知识的人才，从事妇幼保健工作。',
        'what_you_learn': '妇产科学、儿科学、妇幼保健学、儿童保健学、妇女保健学',
        'suitable_for': '对妇幼保健有兴趣的学生。',
        'career_outlook': '医院、妇幼保健院等对妇幼保健医学人才有需求。',
        'xuefeng_comment': '妇幼保健医学是医学类专业，就业稳定。建议对妇幼保健有兴趣的同学报考。',
        'yearly_courses': {'大一': ['系统解剖学、生理学、生物化学、病理学'], '大二': ['妇产科学、儿科学、诊断学、预防医学'], '大三': ['妇幼保健学、儿童保健学、妇女保健学'], '大四': ['妇幼保健院实习', '毕业论文']},
        'top_universities': {'domestic': ['四川大学、北京大学、华中科技大学、南京医科大学'], 'international': ['哈佛大学、约翰霍普金斯大学、伦敦国王学院']}
    },
    {
        'code': '100209T',
        'name': '眼视光学',
        'category': '10 医学',
        'category_icon': '👁️',
        'difficulty': '⭐⭐',
        'salary_range': '¥7k-20k',
        'overview': '眼视光学专业培养掌握眼视光知识的人才，从事眼视光工作。',
        'what_you_learn': '眼科学基础、视光学基础、眼镜学、眼视光器械学、双眼视觉学',
        'suitable_for': '对眼视光学有兴趣的学生。',
        'career_outlook': '视光中心、眼镜公司等对眼视光学人才有需求。',
        'xuefeng_comment': '眼视光学是医学类专业，就业好。建议对眼视光有兴趣的同学报考。',
        'yearly_courses': {'大一': ['大学物理、生理学、生物化学、眼科学基础'], '大二': ['视光学基础、眼镜学、眼视光器械学、双眼视觉学'], '大三': ['斜视弱视学、接触镜学、眼视光应用光学'], '大四': ['视光中心实习', '毕业论文']},
        'top_universities': {'domestic': ['温州医科大学、四川大学、南京医科大学、天津医科大学'], 'international': []}
    },
    {
        'code': '100301T',
        'name': '口腔医学',
        'category': '10 医学',
        'category_icon': '🦷',
        'difficulty': '⭐⭐⭐⭐',
        'salary_range': '¥12k-38k',
        'overview': '口腔医学专业培养掌握口腔医学知识的医生，从事口腔疾病诊疗工作。',
        'what_you_learn': '口腔解剖生理学、口腔组织病理学、口腔内科学、口腔外科学、口腔修复学',
        'suitable_for': '对口腔医学有兴趣的学生。',
        'career_outlook': '医院口腔科、口腔诊所等对口腔医学人才有需求。',
        'xuefeng_comment': '口腔医学是医学类热门专业，就业非常好，待遇高。建议对口腔医学有兴趣的同学报考。',
        'yearly_courses': {'大一': ['系统解剖学、生理学、生物化学、口腔解剖生理学'], '大二': ['口腔组织病理学、诊断学、口腔内科学、口腔外科学'], '大三': ['口腔修复学、口腔正畸学、口腔预防医学'], '大四': ['口腔医院实习', '毕业论文']},
        'top_universities': {'domestic': ['四川大学、北京大学、上海交通大学、武汉大学'], 'international': ['哈佛大学、华盛顿大学、东京医科齿科大学']}
    },
    {
        'code': '100401T',
        'name': '预防医学',
        'category': '10 医学',
        'category_icon': '🌡️',
        'difficulty': '⭐⭐⭐',
        'salary_range': '¥7k-22k',
        'overview': '预防医学专业培养掌握预防医学知识的人才，从事公共卫生工作。',
        'what_you_learn': '流行病学、卫生统计学、环境卫生学、职业卫生学、营养与食品卫生学',
        'suitable_for': '对预防医学和公共卫生有兴趣的学生。',
        'career_outlook': '疾控中心、医院、卫生部门等对预防医学人才有需求。',
        'xuefeng_comment': '预防医学是医学类专业，就业稳定。建议对预防医学有兴趣的同学报考。',
        'yearly_courses': {'大一': ['系统解剖学、生理学、生物化学、无机化学'], '大二': ['卫生统计学、流行病学、环境卫生学、职业卫生学'], '大三': ['营养与食品卫生学、儿童少年卫生学、卫生毒理学'], '大四': ['疾控中心实习', '毕业论文']},
        'top_universities': {'domestic': ['北京大学、复旦大学、华中科技大学、南京医科大学'], 'international': ['哈佛大学、约翰霍普金斯大学、伦敦帝国学院']}
    },
    {
        'code': '100402T',
        'name': '食品卫生与营养学',
        'category': '10 医学',
        'category_icon': '🥗',
        'difficulty': '⭐⭐',
        'salary_range': '¥6k-20k',
        'overview': '食品卫生与营养学专业培养掌握食品卫生与营养学知识的人才，从事营养相关工作。',
        'what_you_learn': '营养学基础、食品卫生学、临床营养学、特殊人群营养学、烹饪营养学',
        'suitable_for': '对食品卫生与营养学有兴趣的学生。',
        'career_outlook': '医院、食品企业、学校等对食品卫生与营养学人才有需求。',
        'xuefeng_comment': '食品卫生与营养学是医学类专业，就业稳定。建议对营养学有兴趣的同学报考。',
        'yearly_courses': {'大一': ['高等数学、无机化学、有机化学、生物化学'], '大二': ['营养学基础、食品卫生学、食品微生物学、食品化学'], '大三': ['临床营养学、特殊人群营养学、烹饪营养学'], '大四': ['医院实习', '毕业论文']},
        'top_universities': {'domestic': ['上海交通大学、南京医科大学、天津医科大学、四川大学'], 'international': ['哈佛大学、约翰霍普金斯大学、伦敦国王学院']}
    },
    {
        'code': '100403T',
        'name': '卫生检验与检疫',
        'category': '10 医学',
        'category_icon': '🔬',
        'difficulty': '⭐⭐',
        'salary_range': '¥7k-22k',
        'overview': '卫生检验与检疫专业培养掌握卫生检验与检疫知识的人才，从事相关工作。',
        'what_you_learn': '卫生微生物学、卫生化学、空气理化检验、水质理化检验、食品理化检验',
        'suitable_for': '对卫生检验与检疫有兴趣的学生。',
        'career_outlook': '疾控中心、卫生监督所等对卫生检验与检疫人才有需求。',
        'xuefeng_comment': '卫生检验与检疫是医学类专业，就业稳定。建议对卫生检验有兴趣的同学报考。',
        'yearly_courses': {'大一': ['高等数学、无机化学、有机化学、分析化学'], '大二': ['卫生微生物学、卫生化学、空气理化检验、水质理化检验'], '大三': ['食品理化检验、生物材料检验、实验室管理学'], '大四': ['疾控中心实习', '毕业论文']},
        'top_universities': {'domestic': ['四川大学、南京医科大学、天津医科大学、重庆医科大学'], 'international': ['哈佛大学、约翰霍普金斯大学、伦敦帝国学院']}
    },
    {
        'code': '100501T',
        'name': '中医学',
        'category': '10 医学',
        'category_icon': '🏥',
        'difficulty': '⭐⭐⭐',
        'salary_range': '¥8k-25k',
        'overview': '中医学专业培养掌握中医学知识的医生，从事中医诊疗工作。',
        'what_you_learn': '中医基础理论、中医诊断学、中药学、方剂学、中医内科学、针灸学',
        'suitable_for': '对中医学有兴趣的学生。',
        'career_outlook': '中医院、中医诊所等对中医学人才有需求。',
        'xuefeng_comment': '中医学是传统医学专业，就业稳定。建议对中医学有兴趣的同学报考。',
        'yearly_courses': {'大一': ['中医基础理论、中医诊断学、中药学、方剂学'], '大二': ['中医基础理论、中医诊断学、中药学、方剂学'], '大三': ['中医内科学、中医外科学、针灸学、推拿学'], '大四': ['中医妇科学、中医儿科学、中医骨伤科学、中医院实习'], '大五': ['中医院实习', '毕业论文']},
        'top_universities': {'domestic': ['北京中医药大学、上海中医药大学、广州中医药大学、南京中医药大学'], 'international': []}
    },
    {
        'code': '100502T',
        'name': '针灸推拿学',
        'category': '10 医学',
        'category_icon': '💉',
        'difficulty': '⭐⭐⭐',
        'salary_range': '¥8k-24k',
        'overview': '针灸推拿学专业培养掌握针灸推拿知识的医生，从事针灸推拿诊疗工作。',
        'what_you_learn': '针灸学、推拿学、经络腧穴学、中医基础理论、中药学',
        'suitable_for': '对针灸推拿有兴趣的学生。',
        'career_outlook': '中医院、针灸推拿科等对针灸推拿学人才有需求。',
        'xuefeng_comment': '针灸推拿学是中医特色专业，就业好。建议对针灸推拿有兴趣的同学报考。',
        'yearly_courses': {'大一': ['中医基础理论、中医诊断学、中药学、方剂学'], '大二': ['经络腧穴学、针法灸法学、推拿手法学、针灸医籍选'], '大三': ['针灸治疗学、推拿治疗学、中医内科学、中医骨伤科学'], '大四': ['中医院实习', '毕业论文']},
        'top_universities': {'domestic': ['北京中医药大学、上海中医药大学、广州中医药大学、南京中医药大学'], 'international': []}
    },
    {
        'code': '100503T',
        'name': '藏医学',
        'category': '10 医学',
        'category_icon': '🏔️',
        'difficulty': '⭐⭐⭐',
        'salary_range': '¥7k-22k',
        'overview': '藏医学专业培养掌握藏医学知识的医生，从事藏医诊疗工作。',
        'what_you_learn': '藏医学基础、藏药学、藏医诊断学、藏医治疗学',
        'suitable_for': '对藏医学有兴趣的学生。',
        'career_outlook': '藏医院等对藏医学人才有需求。',
        'xuefeng_comment': '藏医学是民族医学专业，就业稳定。建议对藏医学有兴趣的同学报考。',
        'yearly_courses': {'大一': ['藏医学基础、藏语基础、藏药学基础'], '大二': ['藏医诊断学、藏药药理学、藏药方剂学'], '大三': ['藏医治疗学、藏医内科学、藏医外科学'], '大四': ['藏医院实习', '毕业论文']},
        'top_universities': {'domestic': ['西藏藏医药大学、青海大学、甘肃中医药大学'], 'international': []}
    },
    {
        'code': '100504T',
        'name': '蒙医学',
        'category': '10 医学',
        'category_icon': '🐴',
        'difficulty': '⭐⭐⭐',
        'salary_range': '¥7k-22k',
        'overview': '蒙医学专业培养掌握蒙医学知识的医生，从事蒙医诊疗工作。',
        'what_you_learn': '蒙医学基础、蒙药学、蒙医诊断学、蒙医治疗学',
        'suitable_for': '对蒙医学有兴趣的学生。',
        'career_outlook': '蒙医院等对蒙医学人才有需求。',
        'xuefeng_comment': '蒙医学是民族医学专业，就业稳定。建议对蒙医学有兴趣的同学报考。',
        'yearly_courses': {'大一': ['蒙医学基础、蒙语基础、蒙药学基础'], '大二': ['蒙医诊断学、蒙药药理学、蒙药方剂学'], '大三': ['蒙医治疗学、蒙医内科学、蒙医外科学'], '大四': ['蒙医院实习', '毕业论文']},
        'top_universities': {'domestic': ['内蒙古医科大学、内蒙古民族大学'], 'international': []}
    },
    {
        'code': '100505T',
        'name': '维医学',
        'category': '10 医学',
        'category_icon': '🏜️',
        'difficulty': '⭐⭐⭐',
        'salary_range': '¥7k-22k',
        'overview': '维医学专业培养掌握维医学知识的医生，从事维医诊疗工作。',
        'what_you_learn': '维医学基础、维药学、维医诊断学、维医治疗学',
        'suitable_for': '对维医学有兴趣的学生。',
        'career_outlook': '维医院等对维医学人才有需求。',
        'xuefeng_comment': '维医学是民族医学专业，就业稳定。建议对维医学有兴趣的同学报考。',
        'yearly_courses': {'大一': ['维医学基础、维语基础、维药学基础'], '大二': ['维医诊断学、维药药理学、维药方剂学'], '大三': ['维医治疗学、维医内科学、维医外科学'], '大四': ['维医院实习', '毕业论文']},
        'top_universities': {'domestic': ['新疆医科大学'], 'international': []}
    },
    {
        'code': '100506T',
        'name': '壮医学',
        'category': '10 医学',
        'category_icon': '🌴',
        'difficulty': '⭐⭐⭐',
        'salary_range': '¥7k-22k',
        'overview': '壮医学专业培养掌握壮医学知识的医生，从事壮医诊疗工作。',
        'what_you_learn': '壮医学基础、壮药学、壮医诊断学、壮医治疗学',
        'suitable_for': '对壮医学有兴趣的学生。',
        'career_outlook': '壮医院等对壮医学人才有需求。',
        'xuefeng_comment': '壮医学是民族医学专业，就业稳定。建议对壮医学有兴趣的同学报考。',
        'yearly_courses': {'大一': ['壮医学基础、壮语基础、壮药学基础'], '大二': ['壮医诊断学、壮药药理学、壮药方剂学'], '大三': ['壮医治疗学、壮医内科学、壮医外科学'], '大四': ['壮医院实习', '毕业论文']},
        'top_universities': {'domestic': ['广西中医药大学'], 'international': []}
    },
    {
        'code': '100507T',
        'name': '哈医学',
        'category': '10 医学',
        'category_icon': '🎪',
        'difficulty': '⭐⭐⭐',
        'salary_range': '¥7k-22k',
        'overview': '哈医学专业培养掌握哈医学知识的医生，从事哈医诊疗工作。',
        'what_you_learn': '哈医学基础、哈药学、哈医诊断学、哈医治疗学',
        'suitable_for': '对哈医学有兴趣的学生。',
        'career_outlook': '哈医院等对哈医学人才有需求。',
        'xuefeng_comment': '哈医学是民族医学专业，就业稳定。建议对哈医学有兴趣的同学报考。',
        'yearly_courses': {'大一': ['哈医学基础、哈语基础、哈药学基础'], '大二': ['哈医诊断学、哈药药理学、哈药方剂学'], '大三': ['哈医治疗学、哈医内科学、哈医外科学'], '大四': ['哈医院实习', '毕业论文']},
        'top_universities': {'domestic': ['新疆医科大学'], 'international': []}
    },
    {
        'code': '100508T',
        'name': '回医学',
        'category': '10 医学',
        'category_icon': '🕌',
        'difficulty': '⭐⭐⭐',
        'salary_range': '¥7k-22k',
        'overview': '回医学专业培养掌握回医学知识的医生，从事回医诊疗工作。',
        'what_you_learn': '回医学基础、回药学、回医诊断学、回医治疗学',
        'suitable_for': '对回医学有兴趣的学生。',
        'career_outlook': '回医院等对回医学人才有需求。',
        'xuefeng_comment': '回医学是民族医学专业，就业稳定。建议对回医学有兴趣的同学报考。',
        'yearly_courses': {'大一': ['回医学基础、阿拉伯语基础、回药学基础'], '大二': ['回医诊断学、回药药理学、回药方剂学'], '大三': ['回医治疗学、回医内科学、回医外科学'], '大四': ['回医院实习', '毕业论文']},
        'top_universities': {'domestic': ['宁夏医科大学'], 'international': []}
    },
    {
        'code': '100509T',
        'name': '中医康复学',
        'category': '10 医学',
        'category_icon': '🏃',
        'difficulty': '⭐⭐',
        'salary_range': '¥7k-22k',
        'overview': '中医康复学专业培养掌握中医康复知识的人才，从事中医康复工作。',
        'what_you_learn': '中医基础理论、针灸学、推拿学、中医康复学、康复评定学',
        'suitable_for': '对中医康复学有兴趣的学生。',
        'career_outlook': '中医院康复科、康复中心等对中医康复学人才有需求。',
        'xuefeng_comment': '中医康复学是新兴专业，需求增长。建议对中医康复有兴趣的同学报考。',
        'yearly_courses': {'大一': ['中医基础理论、中医诊断学、中药学、方剂学'], '大二': ['针灸学、推拿学、中医内科学、康复评定学'], '大三': ['中医康复学、中医养生学、传统体育学'], '大四': ['中医院实习', '毕业论文']},
        'top_universities': {'domestic': ['北京中医药大学、上海中医药大学、南京中医药大学'], 'international': []}
    },
    {
        'code': '100510T',
        'name': '中医养生学',
        'category': '10 医学',
        'category_icon': '🧘',
        'difficulty': '⭐⭐',
        'salary_range': '¥7k-20k',
        'overview': '中医养生学专业培养掌握中医养生知识的人才，从事中医养生工作。',
        'what_you_learn': '中医基础理论、中药学、中医养生学、中医食疗学、中医养生技术',
        'suitable_for': '对中医养生学有兴趣的学生。',
        'career_outlook': '养生馆、中医院等对中医养生学人才有需求。',
        'xuefeng_comment': '中医养生学是新兴专业，需求增长。建议对中医养生有兴趣的同学报考。',
        'yearly_courses': {'大一': ['中医基础理论、中医诊断学、中药学、方剂学'], '大二': ['中医养生学、中医食疗学、传统体育学、中医营养学'], '大三': ['中医养生技术、针灸学、推拿学'], '大四': ['中医院实习', '毕业论文']},
        'top_universities': {'domestic': ['北京中医药大学、上海中医药大学、南京中医药大学'], 'international': []}
    },
    {
        'code': '100511T',
        'name': '中医儿科学',
        'category': '10 医学',
        'category_icon': '👶',
        'difficulty': '⭐⭐⭐',
        'salary_range': '¥8k-24k',
        'overview': '中医儿科学专业培养掌握中医儿科知识的医生，从事中医儿科诊疗工作。',
        'what_you_learn': '中医基础理论、中医诊断学、中药学、方剂学、中医儿科学',
        'suitable_for': '对中医儿科学有兴趣的学生。',
        'career_outlook': '中医院儿科等对中医儿科学人才有需求。',
        'xuefeng_comment': '中医儿科学是医学类专业，就业稳定。建议对中医儿科有兴趣的同学报考。',
        'yearly_courses': {'大一': ['中医基础理论、中医诊断学、中药学、方剂学'], '大二': ['中医基础理论、中医诊断学、中药学、方剂学'], '大三': ['中医儿科学、中医内科学、针灸学'], '大四': ['中医院实习', '毕业论文']},
        'top_universities': {'domestic': ['北京中医药大学、上海中医药大学、南京中医药大学'], 'international': []}
    },
    {
        'code': '100512T',
        'name': '中医骨伤科学',
        'category': '10 医学',
        'category_icon': '🦴',
        'difficulty': '⭐⭐⭐',
        'salary_range': '¥8k-24k',
        'overview': '中医骨伤科学专业培养掌握中医骨伤科学知识的医生，从事骨伤诊疗工作。',
        'what_you_learn': '中医基础理论、中医诊断学、中药学、方剂学、中医骨伤科学',
        'suitable_for': '对中医骨伤科学有兴趣的学生。',
        'career_outlook': '中医院骨伤科等对中医骨伤科学人才有需求。',
        'xuefeng_comment': '中医骨伤科学是医学类专业，就业稳定。建议对中医骨伤有兴趣的同学报考。',
        'yearly_courses': {'大一': ['中医基础理论、中医诊断学、中药学、方剂学'], '大二': ['中医基础理论、中医诊断学、中药学、方剂学'], '大三': ['中医骨伤科学、中医内科学、针灸学'], '大四': ['中医院实习', '毕业论文']},
        'top_universities': {'domestic': ['北京中医药大学、上海中医药大学、广州中医药大学'], 'international': []}
    },
    {
        'code': '100601T',
        'name': '中西医临床医学',
        'category': '10 医学',
        'category_icon': '🏥',
        'difficulty': '⭐⭐⭐',
        'salary_range': '¥8k-25k',
        'overview': '中西医临床医学专业培养掌握中西医结合知识的医生，从事中西医结合诊疗工作。',
        'what_you_learn': '中医基础理论、中药学、诊断学、内科学、外科学、中西医结合内科学',
        'suitable_for': '对中西医结合有兴趣的学生。',
        'career_outlook': '医院、中西医结合医院等对中西医临床医学人才有需求。',
        'xuefeng_comment': '中西医临床医学是医学类专业，就业稳定。建议对中西医结合有兴趣的同学报考。',
        'yearly_courses': {'大一': ['中医基础理论、系统解剖学、生理学、生物化学'], '大二': ['中医诊断学、中药学、方剂学、病理学'], '大三': ['诊断学、内科学、外科学、中西医结合内科学'], '大四': ['医院实习', '毕业论文']},
        'top_universities': {'domestic': ['北京中医药大学、上海中医药大学、广州中医药大学、天津中医药大学'], 'international': []}
    },
    {
        'code': '100701T',
        'name': '药学',
        'category': '10 医学',
        'category_icon': '💊',
        'difficulty': '⭐⭐⭐',
        'salary_range': '¥7k-24k',
        'overview': '药学专业培养掌握药学知识的人才，从事药物研发、生产和使用工作。',
        'what_you_learn': '药物化学、药剂学、药理学、药物分析学、天然药物化学',
        'suitable_for': '对药学有兴趣的学生。',
        'career_outlook': '医院、医药企业、科研机构等对药学人才有需求。',
        'xuefeng_comment': '药学是医学类重要专业，就业好。建议对药学有兴趣的同学报考。',
        'yearly_courses': {'大一': ['高等数学、无机化学、有机化学、物理化学'], '大二': ['生物化学、药物化学、天然药物化学、分析化学'], '大三': ['药剂学、药理学、药物分析学、药事管理学'], '大四': ['医药企业实习', '毕业论文']},
        'top_universities': {'domestic': ['北京协和医学院、北京大学、复旦大学、上海交通大学'], 'international': ['哈佛大学、约翰霍普金斯大学、牛津大学']}
    },
    {
        'code': '100702T',
        'name': '药物制剂',
        'category': '10 医学',
        'category_icon': '💊',
        'difficulty': '⭐⭐',
        'salary_range': '¥7k-22k',
        'overview': '药物制剂专业培养掌握药物制剂知识的人才，从事药物制剂研发和生产工作。',
        'what_you_learn': '药剂学、工业药剂学、物理药剂学、药用高分子材料学、制药工程',
        'suitable_for': '对药物制剂有兴趣的学生。',
        'career_outlook': '医药企业、药物制剂企业等对药物制剂人才有需求。',
        'xuefeng_comment': '药物制剂是药学类专业，就业稳定。建议对药物制剂有兴趣的同学报考。',
        'yearly_courses': {'大一': ['高等数学、无机化学、有机化学、物理化学'], '大二': ['生物化学、药物化学、天然药物化学、分析化学'], '大三': ['药剂学、工业药剂学、物理药剂学、药用高分子材料学'], '大四': ['医药企业实习', '毕业论文']},
        'top_universities': {'domestic': ['中国药科大学、沈阳药科大学、上海交通大学、复旦大学'], 'international': ['哈佛大学、约翰霍普金斯大学、牛津大学']}
    },
    {
        'code': '100703T',
        'name': '临床药学',
        'category': '10 医学',
        'category_icon': '💊',
        'difficulty': '⭐⭐⭐',
        'salary_range': '¥8k-25k',
        'overview': '临床药学专业培养掌握临床药学知识的人才，从事临床药学工作。',
        'what_you_learn': '药剂学、药理学、药物分析学、临床药理学、内科学、外科学',
        'suitable_for': '对临床药学有兴趣的学生。',
        'career_outlook': '医院药房、医药企业等对临床药学人才有需求。',
        'xuefeng_comment': '临床药学是药学类专业，就业好。建议对临床药学有兴趣的同学报考。',
        'yearly_courses': {'大一': ['高等数学、无机化学、有机化学、物理化学'], '大二': ['生物化学、药物化学、药理学、分析化学'], '大三': ['临床药理学、药剂学、药物分析学、诊断学'], '大四': ['医院实习', '毕业论文']},
        'top_universities': {'domestic': ['中国药科大学、沈阳药科大学、北京大学、上海交通大学'], 'international': ['哈佛大学、约翰霍普金斯大学、牛津大学']}
    },
    {
        'code': '100704T',
        'name': '药事管理',
        'category': '10 医学',
        'category_icon': '📋',
        'difficulty': '⭐⭐',
        'salary_range': '¥7k-20k',
        'overview': '药事管理专业培养掌握药事管理知识的人才，从事药事管理工作。',
        'what_you_learn': '药事管理学、药品监管法规、药学概论、管理学基础、市场营销',
        'suitable_for': '对药事管理有兴趣的学生。',
        'career_outlook': '医药企业、药品监管部门等对药事管理人才有需求。',
        'xuefeng_comment': '药事管理是药学类专业，就业稳定。建议对药事管理有兴趣的同学报考。',
        'yearly_courses': {'大一': ['高等数学、管理学基础、经济法、药学概论'], '大二': ['药事管理学、药品监管法规、市场营销、商务谈判'], '大三': ['药物经济学、医药企业管理、公共事业管理'], '大四': ['医药企业实习', '毕业论文']},
        'top_universities': {'domestic': ['中国药科大学、沈阳药科大学、南京中医药大学'], 'international': []}
    },
    {
        'code': '100705T',
        'name': '药物分析',
        'category': '10 医学',
        'category_icon': '🔬',
        'difficulty': '⭐⭐⭐',
        'salary_range': '¥7k-22k',
        'overview': '药物分析专业培养掌握药物分析知识的人才，从事药物分析工作。',
        'what_you_learn': '药物分析学、分析化学、仪器分析、药物化学、药剂学',
        'suitable_for': '对药物分析有兴趣的学生。',
        'career_outlook': '医药企业、药品检验机构等对药物分析人才有需求。',
        'xuefeng_comment': '药物分析是药学类专业，就业稳定。建议对药物分析有兴趣的同学报考。',
        'yearly_courses': {'大一': ['高等数学、无机化学、有机化学、物理化学'], '大二': ['分析化学、仪器分析、药物化学、生物化学'], '大三': ['药物分析学、药剂学、药理学、药物光谱解析'], '大四': ['医药企业实习', '毕业论文']},
        'top_universities': {'domestic': ['中国药科大学、沈阳药科大学、复旦大学、上海交通大学'], 'international': ['哈佛大学、约翰霍普金斯大学']}
    },
    {
        'code': '100706T',
        'name': '药物化学',
        'category': '10 医学',
        'category_icon': '🧪',
        'difficulty': '⭐⭐⭐',
        'salary_range': '¥8k-26k',
        'overview': '药物化学专业培养掌握药物化学知识的人才，从事药物研发工作。',
        'what_you_learn': '药物化学、有机化学、天然药物化学、药理学、药物合成反应',
        'suitable_for': '对药物化学有兴趣的学生。',
        'career_outlook': '医药企业、科研机构等对药物化学人才有需求。',
        'xuefeng_comment': '药物化学是药学类重要专业，就业好。建议对药物化学有兴趣的同学报考。',
        'yearly_courses': {'大一': ['高等数学、无机化学、有机化学、物理化学'], '大二': ['有机化学、分析化学、生物化学、药物化学'], '大三': ['天然药物化学、药物合成反应、药物设计学、药理学'], '大四': ['医药企业实习', '毕业论文']},
        'top_universities': {'domestic': ['中国药科大学、沈阳药科大学、复旦大学、上海交通大学'], 'international': ['哈佛大学、斯坦福大学、麻省理工学院']}
    },
    {
        'code': '100707T',
        'name': '海洋药学',
        'category': '10 医学',
        'category_icon': '🌊',
        'difficulty': '⭐⭐⭐',
        'salary_range': '¥8k-25k',
        'overview': '海洋药学专业培养掌握海洋药学知识的人才，从事海洋药物研发工作。',
        'what_you_learn': '海洋生物学、海洋药物化学、天然药物化学、药物化学、药剂学',
        'suitable_for': '对海洋药学有兴趣的学生。',
        'career_outlook': '医药企业、海洋科研机构等对海洋药学人才有需求。',
        'xuefeng_comment': '海洋药学是新兴专业，前景好。建议对海洋药学有兴趣的同学报考。',
        'yearly_courses': {'大一': ['高等数学、无机化学、有机化学、海洋学'], '大二': ['海洋生物学、生物化学、天然药物化学、药物化学'], '大三': ['海洋药物化学、药剂学、药理学、药物分析学'], '大四': ['医药企业实习', '毕业论文']},
        'top_universities': {'domestic': ['中国海洋大学、上海海洋大学、广东海洋大学'], 'international': ['加州大学圣地亚哥分校、麻省理工学院、东京大学']}
    },
    {
        'code': '100801T',
        'name': '中药学',
        'category': '10 医学',
        'category_icon': '🌿',
        'difficulty': '⭐⭐⭐',
        'salary_range': '¥7k-22k',
        'overview': '中药学专业培养掌握中药学知识的人才，从事中药研发、生产和使用工作。',
        'what_you_learn': '中药学、方剂学、中药鉴定学、中药炮制学、中药药剂学、中药药理学',
        'suitable_for': '对中药学有兴趣的学生。',
        'career_outlook': '中医院、中药企业等对中药学人才有需求。',
        'xuefeng_comment': '中药学是传统专业，就业稳定。建议对中药学有兴趣的同学报考。',
        'yearly_courses': {'大一': ['高等数学、无机化学、有机化学、中医学基础'], '大二': ['中药学、方剂学、中药化学、分析化学'], '大三': ['中药鉴定学、中药炮制学、中药药剂学、中药药理学'], '大四': ['中药企业实习', '毕业论文']},
        'top_universities': {'domestic': ['北京中医药大学、上海中医药大学、广州中医药大学、成都中医药大学'], 'international': []}
    },
    {
        'code': '100802T',
        'name': '中药资源与开发',
        'category': '10 医学',
        'category_icon': '🌿',
        'difficulty': '⭐⭐',
        'salary_range': '¥7k-20k',
        'overview': '中药资源与开发专业培养掌握中药资源与开发知识的人才，从事中药资源工作。',
        'what_you_learn': '中药学、药用植物学、中药资源学、中药栽培学、中药鉴定学',
        'suitable_for': '对中药资源与开发有兴趣的学生。',
        'career_outlook': '中药企业、药用植物园等对中药资源与开发人才有需求。',
        'xuefeng_comment': '中药资源与开发是中药类专业，就业稳定。建议对中药资源有兴趣的同学报考。',
        'yearly_courses': {'大一': ['高等数学、无机化学、有机化学、植物学'], '大二': ['中药学、药用植物学、中药化学、分析化学'], '大三': ['中药资源学、中药栽培学、中药鉴定学、中药炮制学'], '大四': ['中药企业实习', '毕业论文']},
        'top_universities': {'domestic': ['北京中医药大学、南京中医药大学、广州中医药大学'], 'international': []}
    },
    {
        'code': '100803T',
        'name': '中药制药',
        'category': '10 医学',
        'category_icon': '💊',
        'difficulty': '⭐⭐',
        'salary_range': '¥7k-20k',
        'overview': '中药制药专业培养掌握中药制药知识的人才，从事中药制药工作。',
        'what_you_learn': '中药学、中药炮制学、中药药剂学、中药制药工程、制药机械',
        'suitable_for': '对中药制药有兴趣的学生。',
        'career_outlook': '中药企业、制药企业等对中药制药人才有需求。',
        'xuefeng_comment': '中药制药是中药类专业，就业稳定。建议对中药制药有兴趣的同学报考。',
        'yearly_courses': {'大一': ['高等数学、无机化学、有机化学、工程制图'], '大二': ['中药学、中药化学、物理化学、化工原理'], '大三': ['中药炮制学、中药药剂学、中药制药工程、制药机械'], '大四': ['中药企业实习', '毕业论文']},
        'top_universities': {'domestic': ['北京中医药大学、上海中医药大学、南京中医药大学'], 'international': []}
    },
    {
        'code': '100804T',
        'name': '中草药栽培与鉴定',
        'category': '10 医学',
        'category_icon': '🌱',
        'difficulty': '⭐⭐',
        'salary_range': '¥7k-20k',
        'overview': '中草药栽培与鉴定专业培养掌握中草药栽培与鉴定知识的人才，从事相关工作。',
        'what_you_learn': '中药学、药用植物学、植物生理学、中草药栽培学、中药鉴定学',
        'suitable_for': '对中草药栽培与鉴定有兴趣的学生。',
        'career_outlook': '中药企业、药用植物园等对中草药栽培与鉴定人才有需求。',
        'xuefeng_comment': '中草药栽培与鉴定是中药类专业，就业稳定。建议对中草药栽培有兴趣的同学报考。',
        'yearly_courses': {'大一': ['高等数学、无机化学、有机化学、植物学'], '大二': ['中药学、药用植物学、植物生理学、土壤学'], '大三': ['中草药栽培学、中药鉴定学、中药炮制学'], '大四': ['中药企业实习', '毕业论文']},
        'top_universities': {'domestic': ['北京中医药大学、南京中医药大学、成都中医药大学'], 'international': []}
    },
    {
        'code': '100805T',
        'name': '藏药学',
        'category': '10 医学',
        'category_icon': '🏔️',
        'difficulty': '⭐⭐',
        'salary_range': '¥7k-20k',
        'overview': '藏药学专业培养掌握藏药学知识的人才，从事藏药相关工作。',
        'what_you_learn': '藏医学基础、藏药学、藏药炮制学、藏药鉴定学、藏药方剂学',
        'suitable_for': '对藏药学有兴趣的学生。',
        'career_outlook': '藏医院、藏药企业等对藏药学人才有需求。',
        'xuefeng_comment': '藏药学是民族药学专业，就业稳定。建议对藏药学有兴趣的同学报考。',
        'yearly_courses': {'大一': ['藏医学基础、藏语基础、无机化学、有机化学'], '大二': ['藏药学、藏药化学、藏药鉴定学、分析化学'], '大三': ['藏药炮制学、藏药方剂学、藏药制剂学'], '大四': ['藏药企业实习', '毕业论文']},
        'top_universities': {'domestic': ['西藏藏医药大学、青海大学、甘肃中医药大学'], 'international': []}
    },
    {
        'code': '100806T',
        'name': '蒙药学',
        'category': '10 医学',
        'category_icon': '🐴',
        'difficulty': '⭐⭐',
        'salary_range': '¥7k-20k',
        'overview': '蒙药学专业培养掌握蒙药学知识的人才，从事蒙药相关工作。',
        'what_you_learn': '蒙医学基础、蒙药学、蒙药炮制学、蒙药鉴定学、蒙药方剂学',
        'suitable_for': '对蒙药学有兴趣的学生。',
        'career_outlook': '蒙医院、蒙药企业等对蒙药学人才有需求。',
        'xuefeng_comment': '蒙药学是民族药学专业，就业稳定。建议对蒙药学有兴趣的同学报考。',
        'yearly_courses': {'大一': ['蒙医学基础、蒙语基础、无机化学、有机化学'], '大二': ['蒙药学、蒙药化学、蒙药鉴定学、分析化学'], '大三': ['蒙药炮制学、蒙药方剂学、蒙药制剂学'], '大四': ['蒙药企业实习', '毕业论文']},
        'top_universities': {'domestic': ['内蒙古医科大学、内蒙古民族大学'], 'international': []}
    },
    {
        'code': '100807T',
        'name': '维药学',
        'category': '10 医学',
        'category_icon': '🏜️',
        'difficulty': '⭐⭐',
        'salary_range': '¥7k-20k',
        'overview': '维药学专业培养掌握维药学知识的人才，从事维药相关工作。',
        'what_you_learn': '维医学基础、维药学、维药炮制学、维药鉴定学、维药方剂学',
        'suitable_for': '对维药学有兴趣的学生。',
        'career_outlook': '维医院、维药企业等对维药学人才有需求。',
        'xuefeng_comment': '维药学是民族药学专业，就业稳定。建议对维药学有兴趣的同学报考。',
        'yearly_courses': {'大一': ['维医学基础、维语基础、无机化学、有机化学'], '大二': ['维药学、维药化学、维药鉴定学、分析化学'], '大三': ['维药炮制学、维药方剂学、维药制剂学'], '大四': ['维药企业实习', '毕业论文']},
        'top_universities': {'domestic': ['新疆医科大学'], 'international': []}
    },
    {
        'code': '100808T',
        'name': '壮药学',
        'category': '10 医学',
        'category_icon': '🌴',
        'difficulty': '⭐⭐',
        'salary_range': '¥7k-20k',
        'overview': '壮药学专业培养掌握壮药学知识的人才，从事壮药相关工作。',
        'what_you_learn': '壮医学基础、壮药学、壮药炮制学、壮药鉴定学、壮药方剂学',
        'suitable_for': '对壮药学有兴趣的学生。',
        'career_outlook': '壮医院、壮药企业等对壮药学人才有需求。',
        'xuefeng_comment': '壮药学是民族药学专业，就业稳定。建议对壮药学有兴趣的同学报考。',
        'yearly_courses': {'大一': ['壮医学基础、壮语基础、无机化学、有机化学'], '大二': ['壮药学、壮药化学、壮药鉴定学、分析化学'], '大三': ['壮药炮制学、壮药方剂学、壮药制剂学'], '大四': ['壮药企业实习', '毕业论文']},
        'top_universities': {'domestic': ['广西中医药大学'], 'international': []}
    },
    {
        'code': '100901T',
        'name': '法医学',
        'category': '10 医学',
        'category_icon': '🔍',
        'difficulty': '⭐⭐⭐',
        'salary_range': '¥8k-24k',
        'overview': '法医学专业培养掌握法医学知识的人才，从事法医鉴定工作。',
        'what_you_learn': '法医病理学、法医物证学、法医毒物分析、临床法医学、法医法学',
        'suitable_for': '对法医学有兴趣的学生。',
        'career_outlook': '公安部门、司法鉴定机构等对法医学人才有需求。',
        'xuefeng_comment': '法医学是特色专业，就业稳定。建议对法医学有兴趣的同学报考。',
        'yearly_courses': {'大一': ['系统解剖学、生理学、生物化学、病理学'], '大二': ['病理学、药理学、诊断学、内科学'], '大三': ['法医病理学、法医物证学、法医毒物分析、临床法医学'], '大四': ['司法鉴定机构实习', '毕业论文']},
        'top_universities': {'domestic': ['四川大学、复旦大学、中山大学、西安交通大学'], 'international': ['哈佛大学、约翰霍普金斯大学']}
    },
    {
        'code': '101001T',
        'name': '医学检验技术',
        'category': '10 医学',
        'category_icon': '🔬',
        'difficulty': '⭐⭐',
        'salary_range': '¥7k-20k',
        'overview': '医学检验技术专业培养掌握医学检验知识的人才，从事医学检验工作。',
        'what_you_learn': '临床检验基础、生物化学检验、微生物检验、免疫学检验、血液学检验',
        'suitable_for': '对医学检验有兴趣的学生。',
        'career_outlook': '医院检验科、检验中心等对医学检验技术人才有需求。',
        'xuefeng_comment': '医学检验技术是医学辅助专业，就业稳定。建议对医学检验有兴趣的同学报考。',
        'yearly_courses': {'大一': ['系统解剖学、生理学、生物化学、无机化学'], '大二': ['微生物学、免疫学、病理学、临床检验基础'], '大三': ['生物化学检验、微生物检验、免疫学检验、血液学检验'], '大四': ['医院实习', '毕业论文']},
        'top_universities': {'domestic': ['重庆医科大学、首都医科大学、天津医科大学、南京医科大学'], 'international': ['哈佛大学、约翰霍普金斯大学']}
    },
    {
        'code': '101002T',
        'name': '医学实验技术',
        'category': '10 医学',
        'category_icon': '🧪',
        'difficulty': '⭐⭐',
        'salary_range': '¥7k-20k',
        'overview': '医学实验技术专业培养掌握医学实验技术的人才，从事医学实验工作。',
        'what_you_learn': '实验动物学、医学实验技术、分子生物学实验技术、细胞生物学实验技术',
        'suitable_for': '对医学实验技术有兴趣的学生。',
        'career_outlook': '科研机构、医院实验室等对医学实验技术人才有需求。',
        'xuefeng_comment': '医学实验技术是医学辅助专业，就业稳定。建议对医学实验有兴趣的同学报考。',
        'yearly_courses': {'大一': ['高等数学、无机化学、有机化学、生物化学'], '大二': ['生理学、病理学、微生物学、细胞生物学'], '大三': ['实验动物学、医学实验技术、分子生物学实验技术'], '大四': ['科研机构实习', '毕业论文']},
        'top_universities': {'domestic': ['北京大学、复旦大学、上海交通大学、中山大学'], 'international': ['哈佛大学、斯坦福大学']}
    },
    {
        'code': '101003T',
        'name': '医学影像技术',
        'category': '10 医学',
        'category_icon': '📷',
        'difficulty': '⭐⭐',
        'salary_range': '¥7k-20k',
        'overview': '医学影像技术专业培养掌握医学影像技术的人才，从事医学影像技术工作。',
        'what_you_learn': '医学影像设备学、医学影像检查技术、医学影像诊断学、放射治疗技术',
        'suitable_for': '对医学影像技术有兴趣的学生。',
        'career_outlook': '医院影像科等对医学影像技术人才有需求。',
        'xuefeng_comment': '医学影像技术是医学辅助专业，就业稳定。建议对医学影像技术有兴趣的同学报考。',
        'yearly_courses': {'大一': ['系统解剖学、生理学、物理学、生物化学'], '大二': ['病理学、诊断学、医学影像设备学、医学影像物理学'], '大三': ['医学影像检查技术、医学影像诊断学、放射治疗技术'], '大四': ['医院实习', '毕业论文']},
        'top_universities': {'domestic': ['上海健康医学院、重庆医科大学、天津医科大学、南京医科大学'], 'international': ['哈佛大学、约翰霍普金斯大学']}
    },
    {
        'code': '101004T',
        'name': '眼视光学',
        'category': '10 医学',
        'category_icon': '👁️',
        'difficulty': '⭐⭐',
        'salary_range': '¥7k-20k',
        'overview': '眼视光学专业培养掌握眼视光知识的人才，从事眼视光工作。',
        'what_you_learn': '眼科学基础、视光学基础、眼镜学、眼视光器械学、双眼视觉学',
        'suitable_for': '对眼视光学有兴趣的学生。',
        'career_outlook': '视光中心、眼镜公司等对眼视光学人才有需求。',
        'xuefeng_comment': '眼视光学是医学辅助专业，就业好。建议对眼视光有兴趣的同学报考。',
        'yearly_courses': {'大一': ['大学物理、生理学、生物化学、眼科学基础'], '大二': ['视光学基础、眼镜学、眼视光器械学、双眼视觉学'], '大三': ['斜视弱视学、接触镜学、眼视光应用光学'], '大四': ['视光中心实习', '毕业论文']},
        'top_universities': {'domestic': ['温州医科大学、四川大学、南京医科大学、天津医科大学'], 'international': []}
    },
    {
        'code': '101005T',
        'name': '康复治疗学',
        'category': '10 医学',
        'category_icon': '🏃',
        'difficulty': '⭐⭐',
        'salary_range': '¥7k-22k',
        'overview': '康复治疗学专业培养掌握康复治疗知识的人才，从事康复治疗工作。',
        'what_you_learn': '康复评定学、运动疗法、作业疗法、物理因子治疗、言语治疗',
        'suitable_for': '对康复治疗有兴趣的学生。',
        'career_outlook': '医院康复科、康复中心等对康复治疗学人才有需求。',
        'xuefeng_comment': '康复治疗学是新兴专业，需求增长。建议对康复治疗有兴趣的同学报考。',
        'yearly_courses': {'大一': ['系统解剖学、生理学、生物化学、运动学'], '大二': ['康复评定学、功能解剖学、运动疗法、作业疗法'], '大三': ['物理因子治疗、言语治疗、针灸学、推拿学'], '大四': ['康复中心实习', '毕业论文']},
        'top_universities': {'domestic': ['南京医科大学、首都医科大学、上海中医药大学、广州中医药大学'], 'international': ['哈佛大学、约翰霍普金斯大学']}
    },
    {
        'code': '101006T',
        'name': '口腔医学技术',
        'category': '10 医学',
        'category_icon': '🦷',
        'difficulty': '⭐⭐',
        'salary_range': '¥7k-20k',
        'overview': '口腔医学技术专业培养掌握口腔医学技术的人才，从事口腔修复技术工作。',
        'what_you_learn': '口腔解剖生理学、口腔材料学、口腔修复工艺学、牙体解剖学、可摘义齿工艺技术',
        'suitable_for': '对口腔医学技术有兴趣的学生。',
        'career_outlook': '口腔医院、义齿加工企业等对口腔医学技术人才有需求。',
        'xuefeng_comment': '口腔医学技术是医学辅助专业，就业稳定。